# Import node mappings from nodes.py
from .nodes import NODE_CLASS_MAPPINGS as VISION_NODES
from .nodes import NODE_DISPLAY_NAME_MAPPINGS as VISION_DISPLAY_NAMES

# Use direct mappings
NODE_CLASS_MAPPINGS = VISION_NODES
NODE_DISPLAY_NAME_MAPPINGS = VISION_DISPLAY_NAMES

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']